GOAL = popclient
PFAD_POP = ../data/
PFAD_USERDATA = ../userdata/
LIBS = `allegro-config --shared` -lefence -lgpc
#LIBS = `allegro-config --shared`
DEFS = -DLINUX -DPFAD_POP='"$(PFAD_POP)"' -DPFAD_USERDATA='"$(PFAD_USERDATA)"'
ADDCFLAGS =
ADDPFLAFS =
DEBUGFLAGS = -g

include Makefile.common
